FROM node:latest

# set working directory
RUN mkdir /app
WORKDIR /app

# install and cache app dependencies
COPY src /app/src
COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json
RUN npm install

# start app
CMD ["npm", "start"]
