FROM node:9.9.0

# set working directory
RUN mkdir /app
WORKDIR /app

# install and cache app dependencies
COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json
COPY lib /app/lib
RUN npm install

COPY src /app/src
COPY webpack.config.js /app/webpack.config.js

# start app
CMD ["npm", "start"]
