FROM node:9.7.1

# set working directory
RUN mkdir /app
WORKDIR /app

# install and cache app dependencies
COPY package.json /app/package.json
COPY package-lock.json /app/package-lock.json
COPY lib /app/lib
RUN npm install

# start app
CMD ["npm", "run", "watch"]